config/routes.rb
Rails.application.routes.draw do

  get 'pins/tagged/:id' => 'pins#tag', :as => :tags

  devise_for :users, controllers: {
  registrations: 'users/registrations',
  sessions: 'users/sessions'
  }

  resources :pins do
    member do
      post 'upvote', to: "pins#upvote", :as => :upvote
      post 'downvote', to: "pins#downvote", :as => :downvote
    end
  end

  root 'pins#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base

  belongs_to :user
  acts_as_taggable
  acts_as_votable

  attachment :file

  validates :image, allow_blank: true, format: { with: %r{\.gif\z}, message: 'must be a .gif image.' }

  def score
    self.get_upvotes.size - self.get_downvotes.size
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins, dependent: :destroy

  acts_as_voter



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  # GET /pins
  # GET /pins.json
  def index
    @pin = Pin.new
    @pins = Pin.all
    if params[:tag]
      @pins = Pin.tagged_with(params[:tag]).page params[:page]
    else
      @pins = Pin.all.page params[:page]
    end
      respond_to do |format|
        format.js {}
        format.html {:back}
      end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
      respond_to do |format|
       format.html {}
      end
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)
    @pin.user_id = current_user.id

    if @pin.save!
      respond_to do |format|
        format.js {}
      end
    else
      respond_to do |format|
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @pin.liked_by current_user
		respond_to do |format|
      format.js{}
    end
	end

  def downvote
    @pin.downvote_from current_user
    respond_to do |format|
      format.js{ render 'upvote.js'}
    end
  end


  # Used a short tutorial to help me get started http://alexmuraro.me/posts/acts-as-taggable-on-a-short-tutorial/.
  def tag
    @pins = Pin.tagged_with(params[:id])
    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:title, :image, :tag_list, :file_id)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @pin = Pin.new
    super
  end

  # POST /resource
  def create
    @pin = Pin.new
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    @pin = Pin.new
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper

  include ActsAsTaggableOn::TagsHelper



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OMG</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="wrapper">
      <nav role="navigation" class="navbar navbar-inverse">
        <div class="container">
          <div class="navbar-header">
              <%= link_to "OMG Gifs 'n' Stuffs", root_path, class: "navbar-brand" %>
          </div>

          <div id="navbar">
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><%= link_to "New Pin", "#", :id => "new_link_modal", "data-toggle" => "modal", "data-target" => "#myModalform" %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
              <% else %>
                <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %></li>
                <li><%= link_to "Sign In", user_session_path, :class => 'navbar-link' %></li>
              <% end %>
              <%= form_tag "#", :method => :get, class: "navbar-form navbar-left" do %>
                <%= text_field_tag :search_item, params[:search_item], placeholder: 'Search...', :autocomplete => :off, class: "form-control"  %>
                <%= submit_tag "Search", class: "btn btn-primary" %>
              <% end %>
                <%= render :partial => "pins/form", :locals => {:title => "New Pin", :id => "NewPin"} %>
            </ul>
          </div>
        </div>
      </nav>

      <!-- Shows errors when one is present -->
      <div class="container">
        <div class="text-center col-xs-3 col-xs-offset-9">
          <% if flash[:error] %>
            <p class='error'><%=h flash[:error] %></p>
          <% end %>
          <% if flash[:notice] %>
            <p class='notice'><%=h flash[:notice] %></p>
          <% end %>
        </div>

        <%= yield %>

      </div>
    </div>
    <div class="footer"></div>
  </body>
</html>

app/views/pins/_form.html.erb
<div class="modal fade" id="myModalform" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">A New Pin</h4>
      </div>
      <div class="modal-body">
        <%= bootstrap_form_for @pin, :remote => true do |f| %>

          <% if @pin.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@pin.errors.count, "error") %>
                prohibited this pin from being saved:</h2>
          <% end %>

          <div class="field">
            <%= f.text_field :title %>
          </div>
          <div class="field">
            <%= f.text_field :image, :placeholder => "http://" %>
            <%= f.attachment_field :file %>
          </div>
          <div class="field">
            <%= f.text_field :tag_list %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/pins/_pin.html.erb
<div class="panel panel-default">
  <% if gif.file.blank? %>
    <div class="panel-thumbnail"><%= link_to image_tag(gif.image, :class => "img-responsive"), "#", "data-toggle" => "modal", "data-target" => "#myModal#{gif.id}" %></div>
  <% else %>
    <div class="panel-thumbnail"><%= link_to image_tag(attachment_url(gif, :file), :class => "img-responsive"), "#", "data-toggle" => "modal", "data-target" => "#myModal#{gif.id}" %></div>
  <% end %>
</div>

app/views/pins/_pinrow.html.erb
<div class="row">
  <% pin.each do |gif| %>
    <div class="col-xs-3">
      <%= render partial: 'show', :locals => {:gif => gif} %>
      <%= render partial: "pin", :locals => {:gif => gif} %>
      <%= render partial: 'pins/tags', :locals => {:gif => gif} %>
    </div>
  <% end %>
</div>

app/views/pins/_show.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal<%= gif.id %>" role="dialog">
  <div class="modal-dialog">

<!-- Modal content?-->
    <div class="modal-content">
      <div class="modal-header">
        <button aria-label="Close" class="close" data-dismiss="modal" type="button">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel"><%= gif.title %></h4>
      </div>
      <div class="modal-body">
        <% if gif.file.blank? %>
          <%= image_tag(gif.image) %>
        <% else %>
          <%= image_tag(attachment_url(gif, :file)) %>
        <% end %>
      </div>
       <%= render partial: 'pins/voting', :locals => {:gif => gif} %>
      </div>
    </div>
  </div>

app/views/pins/_tags.html.erb
<div class="panel-body" id="updatescore">
  <p class="lead"><%= gif.title %></p>
  <p><%= pluralize(gif.score, "vote") %></p>
  <p>
    <% gif.tags.any? %>
      <% gif.tags.each do |tag| %>
        <%= link_to tag.name, tags_path(tag.name), remote: true %>
      <% end %>
  </p>
</div>

app/views/pins/_voting.html.erb
<div class="modal-footer" id="votebase">
  <ul class="list-inline">
    <li><%= time_ago_in_words(gif.created_at) %> ago by <%= gif.user.email %></li>
  </ul>
  <div classe="well"><%= gif.image || attachment_url(gif, :file) %></div>
  <% if user_signed_in? %>
    <%= link_to 'Edit', edit_pin_path(gif), class: "btn btn-default btn-sm" %>
      <div class="btn-group">
        <ul class="list-inline">
        <% if current_user.voted_up_on?(gif) %>
          <%= button_to upvote_pin_path(gif), class: "btn btn-default btn-sm", remote: true do %>
            <li class="disabled"><i class="glyphicon glyphicon-chevron-up"> Upvote</i></li>
          <% end %>
          <%= button_to downvote_pin_path(gif), class: "btn btn-default btn-sm", remote: true do %>
            <li class="glyphicon glyphicon-chevron-down"> Downvote </li>
          <% end %>
        <% elsif current_user.voted_down_on?(gif) %>
          <%= button_to upvote_pin_path(gif), class: "btn btn-default btn-sm", remote: true do %>
            <li class="glyphicon glyphicon-chevron-up"> Upvote</li>
          <% end %>
          <%= button_to downvote_pin_path(gif), class: "btn btn-default btn-sm", remote: true do %>
            <li class="disabled"><i class="glyphicon glyphicon-chevron-down"> Downvote </i></li>
          <% end %>
        <% else %>
          <%= button_to upvote_pin_path(gif), class: "btn btn-default btn-sm", remote: true do %>
            <li class="glyphicon glyphicon-chevron-up"> Upvote</li>
          <% end %>
          <%= button_to downvote_pin_path(gif), class: "btn btn-default btn-sm", remote: true do %>
            <li class="glyphicon glyphicon-chevron-down"> Downvote </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>
    <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
</div>

app/views/pins/create.js.erb
$("#pin_list").prepend('<%=escape_javascript(render :partial => 'pinrow', :locals => {:pin => [@pin]}) %>');
resetForm($('#myModalform'));
$('.modal-backdrop').open();
$("#myModal").modal('hide');

app/views/pins/downvote.js.erb
$('.modal-backdrop').hide();
$('.modal').modal('hide');
$('#votebase').html('<%= escape_javascript( render :partial => "pins/voting", :locals => {:gif => @pin}) %>');
$("#pin_list").html('<%=escape_javascript(render :partial => "pinrow", :locals => {:pin => Pin.all}) %>');

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %>
<%= link_to 'destroy', pin_path(@pin),
                         :method => :delete,
                         :data => { :confirm => 'Are you sure?'},
                         :class => 'btn btn-xs btn-danger' %>
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div class"container" id="pin_list">
  <% @pins.each_slice(4) do |pin| %>
    <%= render partial: 'pinrow', :locals => {:pin => pin} %>
  <% end %>
</div>

app/views/pins/index.js.erb
$("#updatescore").html('<%=escape_javascript(render :partial => 'tags', :locals => {:gif => pin}) %>');

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/tag.js.erb
$('#updatescore').html('<%= escape_javascript( render :layout => "pins/show", :locals => {:pin => Pin.all}) %>');

app/views/pins/upvote.js.erb
$('.modal').modal('hide');
$('.modal-backdrop').hide();
$('#votebase').html('<%= escape_javascript( render :partial => "pins/voting", :locals => {:gif => @pin}) %>');
$("#pin_list").html('<%=escape_javascript(render :partial => "pinrow", :locals => {:pin => Pin.all}) %>');